### ISSUE TITLE
excuse me

### ISSUE THREAD

**Issue by luozhili1999** [BasketBandit/nooksworkbench.com#1]
Where is the price of the items on the website.   Manual entry？ or  
Other websites？
I want to make sure the data is accurate  
I want to make a website about that price in chinese  
thanks : )

**Comment by BasketBandit** [comment]
I get all item data from this source: https://docs.google.com/spreadsheets/d/13d_LAJPlxMa_DubPTuirkIV4DERBMXbrWQsmSh8ReK4/edit?usp=drivesdk
